CREATE TABLE IF NOT EXISTS JOBSEEKERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PHONE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DOB DATE NOT NULL,
    HIGHEST_DEGREE VARCHAR(100) NOT NULL,
    SPECIALIZATION VARCHAR(100) NOT NULL,
    WORK_EXPERIENCE INT NOT NULL,
    PHONE_OTP VARCHAR(6),
    PHONE_OTP_EXPIRY DATETIME,
    EMAIL_OTP VARCHAR(6),
    EMAIL_OTP_EXPIRY DATETIME,
    IS_VERIFIED TINYINT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS EMPLOYERS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PHONE_NUMBER VARCHAR(10) UNIQUE NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    COMPANY_NAME VARCHAR(100) NOT NULL,
    PHONE_OTP VARCHAR(6),
    PHONE_OTP_EXPIRY DATETIME,
    EMAIL_OTP VARCHAR(6),
    EMAIL_OTP_EXPIRY DATETIME,
    IS_VERIFIED TINYINT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS JOBS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    JOB_TITLE VARCHAR(100) NOT NULL,
    SPECIALIZATION VARCHAR(100) NOT NULL,
    MINIMUM_WORK_EXPERIENCE INT NOT NULL,
    LOCATION VARCHAR(100) NOT NULL,
    SALARY INT NOT NULL,
    EMPLOYER_ID INT NOT NULL,
    UNIQUE (JOB_TITLE, SPECIALIZATION, MINIMUM_WORK_EXPERIENCE, LOCATION, SALARY, EMPLOYER_ID),
    FOREIGN KEY (EMPLOYER_ID) REFERENCES EMPLOYERS(ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS JOB_APPLICATIONS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    RESUME_NAME VARCHAR(255) NOT NULL,
    RESUME_DATA LONGBLOB NOT NULL,
    JOB_ID INT NOT NULL,
    JOBSEEKER_ID INT NOT NULL,
    UNIQUE (JOB_ID, JOBSEEKER_ID),
    FOREIGN KEY (JOB_ID) REFERENCES JOBS(ID) ON DELETE CASCADE,
    FOREIGN KEY (JOBSEEKER_ID) REFERENCES JOBSEEKERS(ID) ON DELETE CASCADE
);
